site_name: RVC-OneDriveDocs
site_url: https://TimSoenksen.github.io/RVC-OneDriveDocs/

#set up the material theme (use pip install mkdocs-material to install)
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

#site navigation
nav:
  - Home: index.md