site_name: RVC-OneDriveDocs
site_url: https://TimSoenksen.github.io/RVC-OneDriveDocs/

#set up the material theme (use pip install mkdocs-material to install)
theme:
  name: material

#site navigation
nav:
  - Home: index.md